# Generated by Django 4.1.1 on 2022-09-21 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('my_id', models.AutoField(primary_key=True, serialize=False)),
                ('mobile', models.IntegerField(unique=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
