# Generated by Django 4.1.1 on 2022-09-21 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='users',
            table='register',
        ),
    ]
