# Generated by Django 4.1.1 on 2022-09-22 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0002_alter_users_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='mobile',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
