# Generated by Django 4.1.1 on 2022-09-22 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0003_alter_users_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='my_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
