# Generated by Django 4.1.1 on 2022-09-23 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0005_alter_users_my_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('u_id', models.IntegerField()),
                ('my_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('desc', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(upload_to='Media/')),
            ],
            options={
                'db_table': 'posts',
            },
        ),
    ]
