# Generated by Django 4.1.1 on 2022-09-23 18:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0006_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='my_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
